### ISSUE TITLE
Purchase error

### ISSUE THREAD

**Issue by Ricoroma** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#235]
Hello, all last 2 months purchasing wasn't causing any problems, but today i have all 403 with comment purchase_not_allowed. Could it be caused by recent policy changes, or only code problems?

**Comment by LeleDerGrasshalmi** [comment]
Hey, could you please share the full error respons (json)

**Comment by ricoroma2** [comment]
well i couldn't trigger this error by myself since then, so this is probably solved

although i have other question: does api provide data about every user's match? so i can do some analysis on recent matches etc. (i remember that StatsProxy provides some info about matches, but this info is about all time)

**Comment by LeleDerGrasshalmi** [comment]
such apis are not publicy available

**Comment by LeleDerGrasshalmi** [comment]
no, there are no parameters

**Comment by ricoroma2** [comment]
sad but ok

also, is there any reason for fact that every time i call this method, i am given different amount of accounts?

**Comment by LeleDerGrasshalmi** [comment]
probs random caching on epics side, we cant do anything about it

**Comment by ricoroma2** [comment]
ok, thanks
