### ISSUE TITLE
Error with platformToken endpoint

### ISSUE THREAD

**Issue by Damnbuoy** [LeleDerGrasshalmi/FortniteEndpointsDocumentation#350]
### Issue Checklist

- [X] I have properly named the issue
- [X] I looked in issues/discussions, if my question was previously anwsered

### What is the Request Method?

POST

### What is the Request URL?

https://account-public-service-prod.ol.epicgames.com/account/api/public/account/{self.account_id}/platformToken/xbl_xtoken/cfaa14c4bf8744e3a5ef9a5d6c34558d

### What is the Response Status Code?

401

### What is the Response Content? (if applicable)

{"errorCode":"errors.com.epicgames.account.external_auth_validate_failed","errorMessage":"secondaryAccountIds should contain at least one item (a XUID) for xbl methods.","messageVars":[],"numericErrorCode":18063,"originatingService":"com.epicgames.account.public","intent":"prod"}

### Additional Context (if applicable)

Im using "rp://epicgames.com/" relying party to get the exchange code. Whats the cause of this error? I dont know what secondaryaccountIds its talking about :c

**Comment by Jaren8r** [comment]
The xbl_xtoken external auth type has never been fully figured out. Previously this gave a database timeout error, but now it gives this error. I'll update the documentation on this.

**Comment by Damnbuoy** [comment]
I need to redeem xbox purchases. Is there any other workaround for that?

**Comment by Jaren8r** [comment]
1. RedeemRealMoneyPurchases takes the XSTS token directly for MicrosoftStore, there is no platform token involved here (platform tokens are only for psn and ubisoft afaik).
2. I don't believe it's possible to generate an XSTS token that will work there. I'm assuming it needs the XSTS to contain a title token for Fortnite, but that's not possible to get without having device authorization of a real console (since the xbox version of fn is only supported on consoles).

**Comment by Damnbuoy** [comment]
thanks alot.
